# Generated by Django 4.2.25 on 2025-10-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LOCATION_MASTER',
                'index_together': {('location', 'status')},
            },
        ),
        migrations.CreateModel(
            name='MoveInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_moves', to='inventory.locationmaster')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_moves', to='inventory.locationmaster')),
            ],
            options={
                'db_table': 'MOVE_INVENTORY',
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('original_quantity', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_details', to='inventory.locationmaster')),
            ],
            options={
                'db_table': 'STOCK_DETAIL',
                'unique_together': {('sku_code', 'location')},
                'index_together': {('sku_code', 'location', 'quantity')},
            },
        ),
    ]
